services:
  postgres:
    image: postgres:17
    container_name: dam-postgres

    restart: unless-stopped

    env_file:
      - .env.development

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - dam-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    container_name: dam-rabbitmq

    restart: unless-stopped

    env_file:
      - .env.development



    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - dam-network

    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: dam-minio

    restart: unless-stopped

    env_file:
      - .env.development

    command: server /data --console-address ":9001"


    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio-data:/data

    networks:
      - dam-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/minio/health/live || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: dam-api:latest

    build:
      context: .
      dockerfile: services/api/Dockerfile

    container_name: dam-api

    restart: unless-stopped

    env_file:
      - .env.development

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy

    
    ports:
      - "5001:5001"

    networks:
      - dam-network

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:5001/v1/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  worker:
    image: dam-background-processor:latest

    build:
      context: .
      dockerfile: worker/background-processor/Dockerfile

    container_name: dam-worker

    restart: unless-stopped

    env_file:
      - .env.development

    environment:
      WORKER_TYPE: video

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
      api:
        condition: service_healthy

    networks:
      - dam-network

  web:
    image: dam-web:latest

    build:
      context: .
      dockerfile: apps/web/Dockerfile

    container_name: dam-web

    restart: unless-stopped

    depends_on:
      api:
        condition: service_healthy

    ports:
      - "5173:80"

    networks:
      - dam-network

volumes:
  postgres-data:
  minio-data:

networks:
  dam-network:
    driver: bridge